
work_dir: ./work_dir/ntu/xview/msg3d_bone

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/ntu/xview/train_data_bone.npy
  label_path: ./data/ntu/xview/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False
  debug: True

test_feeder_args:
  data_path: ./data/ntu/xview/val_data_bone.npy
  label_path: ./data/ntu/xview/val_label.pkl
  debug: True

# model
model: model.msg3d.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

# optim
weight_decay: 0.0005
base_lr: 0.1
step: [5, 10]

# training
num_epoch: 10
device: [0,1,2,3]
batch_size: 16
forward_batch_size: 16
test_batch_size: 16
nesterov: True

